# Describes the format for available fan services

set_night_mode:
  description: Set the fan in night mode.
  fields:
    entity_id:
      description: Name(s) of the entities to enable/disable night mode
      example: "fan.living_room"
    night_mode:
      description: Night mode status
      example: true

set_auto_mode:
  description: Set the fan in auto mode.
  fields:
    entity_id:
      description: Name(s) of the entities to enable/disable auto mode
      example: "fan.living_room"
    auto_mode:
      description: Auto mode status
      example: true

set_timer:
  description: Set the sleep timer.
  fields:
    entity_id:
      description: Name(s) of the entities to set the sleep timer for
      example: "fan.living_room"
    timer:
      description: The value in minutes to set the timer to, 0 to disable it
      example: 30

set_speed:
  description: Set the exact speed of the fan.
  fields:
    entity_id:
      description: Name(s) of the entities to set the speed for
      example: "fan.living_room"
    dyson_speed:
      description: Speed
      example: 1
